### ISSUE TITLE
Foundry v12 plans

### ISSUE THREAD

**Issue by reckenrode** [reckenrode/nix-foundryvtt#17]
The first prototype of Foundry v12 is available. Here are the plans for Foundry going forward:

- [x] Add a foundry_12 package.
- [x] Deprecate the unversioned foundry package, leaving it as an alias for foundry_11.
- [x] Add metadata for prototype/beta/release/etc to `versions.json`.
- [x] Default only to release versions but allow opt in to pre-release, beta, etc.

The idea is to avoid breaking user setups by being conservative about releases while allowing opting into non-release versions.

**Comment by JonBoyleCoding** [comment]
A bit late to the party, but this sounds sensible to me.

**Comment by reckenrode** [comment]
FoundryVTT 12 is out. I’ll try to take a look at making these changes this weekend.

**Comment by reckenrode** [comment]
Note, that as indicated: `foundry` will be an alias to `foundry_11` and issue a warning. If you want to use Foundry v12, you’ll need to manually upgrade since there are [breaking changes](https://github.com/orgs/foundryvtt/projects/42/views/9) from prior stable releases.

**Comment by reckenrode** [comment]
Implemented by https://github.com/reckenrode/nix-foundryvtt/commit/82bda5944eaed1686f8eabe41f768a17898ec547.
