### ISSUE TITLE
Package versions don't calculate Major Version correctly.

### ISSUE THREAD

**Issue by Faeranne** [reckenrode/nix-foundryvtt#18]
As of right now, many v10 packages will never install correctly as they are identified as v11.  This includes the default v10 version, which nix-foundryvtt incorrectly identifies as `11.310`.  Given build numbers are now interwoven between major versions, it seems necessary to either manually use the `version` attribute and set it correctly from the start instead of rebuilding it, or to correctly extract the major version listed in `version`.

**Comment by reckenrode** [comment]
Hi @Faeranne, I apologize for the delay fixing this issue. I’d been maintaining an exception list of version mappings, but I neglected to update it for the last few v10 releases. It should be calculating the version correctly now. Please let me know if it still doesn’t work for you.
