### ISSUE TITLE
warning: foundryvtt.service is ordered after 'network-online.target' but doesn't depend on it

### ISSUE THREAD

**Issue by Sntx626** [reckenrode/nix-foundryvtt#19]
This warning is thrown when evaluating the module.

**Comment by reckenrode** [comment]
Hi @Sntx626, thanks for the report. I believe this should be fixed in 0e61d84. Please let me know if it it’s not. (My server is offline right now, so I can’t test, but I followed other config used in nixpkgs.)

**Comment by Sntx626** [comment]
I can confirm, the warning is resolved when using the latest commit.
