### ISSUE TITLE
dataDir doesn't work for any other than the default value

### ISSUE THREAD

**Issue by anriha** [reckenrode/nix-foundryvtt#25]
Currently, if you specify any other dataDir path, foundry will not work as it doesn't have permission to write there. Currently, StateDirectory is used to give permissions to correspoding directory, but this only gives write permissions to `/var/lib/foundryvtt`. 

For now as a workaround I use 
```nix
ReadWritePaths = [ "${config.services.foundryvtt.dataDir}" ];
```
This works, but it isn't the best approach, as StateDirectory is basically useless at that point.

**Comment by reckenrode** [comment]
I pushed a fix to https://github.com/reckenrode/nix-foundryvtt/tree/push-kmkmuprzxtny. Can you test and confirm whether this resolves your issue?

**Comment by anriha** [comment]
Thank you, that does seem to work.
