### ISSUE TITLE
`ReadOnlyPaths = true` is invalid

### ISSUE THREAD

**Issue by Kha** [reckenrode/nix-foundryvtt#3]
Thanks for this flake! Minor nit: `ReadOnlyPath` seems to expect a list of paths, not a Boolean.
```
systemd[1]: /etc/systemd/system/foundryvtt.service:35: ReadOnlyPaths= path is not absolute, ignoring: true
```

**Comment by reckenrode** [comment]
Thanks for the report. I’ve noticed in the log before but didn’t bother to fix it. I pushed a commit that properly sets the readonly paths.
